name: Changelog

on:
  workflow_dispatch:

  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
